In [5]:
# Import the necessary liabraries
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow import keras
from sklearn.model_selection import train_test_split
from tensorflow.keras import layers

In [ ]:
# Activation functions (Binary sigmoid)
# Layers
# Forwar & Backword Propogation
# Loss Function
# Optimizer
# Epochs

In [7]:

np.random.seed(42)

# Number of rows for this
n = 500

# Input features

annual_income = np.random.randint(20000, 200000, n)
credit_score = np.random.randint(300, 850, n)
loan_amount = np.random.randint(5000, 100000, n)
employment_years = np.random.randint(0, 30, n)

# Output Feature

loan_approved = (
    (annual_income > 50000) &
     (credit_score > 600 ) &
    (loan_amount < annual_income * 0.8)
).astype(int)

In [8]:
df = pd.DataFrame({
    'annual_income': annual_income,
    'credit_score': credit_score,
    'loan_amount': loan_amount,
    'employment_years': employment_years,
    'loan_approved': loan_approved
})

In [9]:
df

     annual_income  credit_score  loan_amount  employment_years  loan_approved
0           141958           389        92895                23              0
1           166867           717        51240                12              1
2           151932           414        42148                 2              0
3           123694           495        99270                15              0
4           139879           800         9757                 5              1
..             ...           ...          ...               ...            ...
495         117532           478        71672                22              0
496         112658           481        39832                 7              0
497         143633           324        36966                17              0
498         120386           479        77545                20              0
499          47350           800        17987                 0              0

[500 rows x 5 columns]

In [22]:
df.shape[1]

5

In [11]:
df.columns

Index(['annual_income', 'credit_score', 'loan_amount', 'employment_years',
       'loan_approved'],
      dtype='object')

In [12]:
df.loan_approved.value_counts()

loan_approved
0    353
1    147
Name: count, dtype: int64

In [13]:
X = df[['annual_income', 'credit_score', 'loan_amount', 'employment_years']]
y = df['loan_approved']

In [15]:
X.head(3)

   annual_income  credit_score  loan_amount  employment_years
0         141958           389        92895                23
1         166867           717        51240                12
2         151932           414        42148                 2

In [17]:
# Scaling
# Normalization
# Standardization
X_min = X.min()
X_max = X.max()
X_scaled = (X - X_min) / (X_max - X_min)

In [18]:
X_scaled

     annual_income  credit_score  loan_amount  employment_years
0         0.676172      0.162113     0.925807          0.793103
1         0.815152      0.759563     0.486751          0.413793
2         0.731822      0.207650     0.390918          0.068966
3         0.574269      0.355191     0.993001          0.517241
4         0.664572      0.910747     0.049508          0.172414
..             ...           ...          ...               ...
495       0.539888      0.324226     0.702110          0.758621
496       0.512693      0.329690     0.366507          0.241379
497       0.685518      0.043716     0.336299          0.586207
498       0.555812      0.326047     0.764013          0.689655
499       0.148308      0.910747     0.136254          0.000000

[500 rows x 4 columns]

In [20]:
# Training - Testing Spliting
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

In [23]:
# Model Creating
model = keras.Sequential([
    layers.Input(shape = (X_train.shape[1],)), # Input Layer
    layers.Dense(8,activation='relu'), # Hidden Layer
    layers.Dense(1,activation='sigmoid') # Output Layer
])

In [25]:
model.compile(optimizer='sgd',loss='binary_crossentropy',metrics=['accuracy'])

In [27]:
history = model.fit(X_train,y_train, validation_data=(X_test,y_test),
                    epochs = 100, batch_size = 4, verbose=1)

Epoch 1/100
100/100 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.4300 - loss: 0.7157 - val_accuracy: 0.6200 - val_loss: 0.6552
Epoch 2/100
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8425 - loss: 0.6092 - val_accuracy: 0.8800 - val_loss: 0.5979
Epoch 3/100
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8600 - loss: 0.5711 - val_accuracy: 0.8500 - val_loss: 0.5704
Epoch 4/100
100/100 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8200 - loss: 0.5471 - val_accuracy: 0.8200 - val_loss: 0.5500
Epoch 5/100
100/100 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8175 - loss: 0.5283 - val_accuracy: 0.8000 - val_loss: 0.5337
Epoch 6/100
100/100 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8150 - loss: 0.5122 - val_accuracy: 0.8000 - val_loss: 0.5199
Epoch 7/100
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8175 - loss: 0.4977 - val_accuracy: 0.8200 - val_loss: 0.5081
Epoch 8/100
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8250 - loss: 0.4832 - val_accuracy: 0.8400 - val_loss: 0.4979
Epoch 9/100
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8625 - loss: 0.4698 - val_accuracy: 0.8400 - val_loss: 0.4856
Epoch 10/100
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8725 - loss: 0.4563 - val_accuracy: 0.8300 - val_loss: 0.4733
Epoch 11/100
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8750 - loss: 0.4435 - val_accuracy: 0.8400 - val_loss: 0.4622
Epoch 12/100
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8750 - loss: 0.4308 - val_accuracy: 0.8800 - val_loss: 0.4523
Epoch 13/100
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8925 - loss: 0.4178 - val_accuracy: 0.8800 - val_loss: 0.4414
Epoch 14/100
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8900 - loss: 0.4061 - val_accuracy: 0.8900 - val_loss: 0.4317
Epoch 15/100
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8950 - loss: 0.3942 - val_accuracy: 0.8800 - val_loss: 0.4234
Epoch 16/100
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8975 - loss: 0.3831 - val_accuracy: 0.8900 - val_loss: 0.4128
Epoch 17/100
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8900 - loss: 0.3725 - val_accuracy: 0.8600 - val_loss: 0.4044
Epoch 18/100
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9100 - loss: 0.3621 - val_accuracy: 0.8600 - val_loss: 0.3963
Epoch 19/100
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9125 - loss: 0.3526 - val_accuracy: 0.8600 - val_loss: 0.3877
Epoch 20/100
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9150 - loss: 0.3429 - val_accuracy: 0.8600 - val_loss: 0.3793
Epoch 21/100
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9075 - loss: 0.3348 - val_accuracy: 0.8700 - val_loss: 0.3728
Epoch 22/100
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9125 - loss: 0.3262 - val_accuracy: 0.8600 - val_loss: 0.3651
Epoch 23/100
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9050 - loss: 0.3185 - val_accuracy: 0.8600 - val_loss: 0.3595
Epoch 24/100
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9100 - loss: 0.3109 - val_accuracy: 0.8600 - val_loss: 0.3522
Epoch 25/100
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9100 - loss: 0.3044 - val_accuracy: 0.8600 - val_loss: 0.3464
Epoch 26/100
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9100 - loss: 0.2975 - val_accuracy: 0.8700 - val_loss: 0.3411
Epoch 27/100
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9100 - loss: 0.2914 - val_accuracy: 0.8600 - val_loss: 0.3365
Epoch 28/100
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9125 - loss: 0.2855 - val_accuracy: 0.8600 - val_loss: 0.3313
Epoch 29/100
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9125 - loss: 0.2798 - val_accuracy: 0.8700 - val_loss: 0.3265
Epoch 30/100
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9125 - loss: 0.2746 - val_accuracy: 0.8700 - val_loss: 0.3219
Epoch 31/100
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9125 - loss: 0.2700 - val_accuracy: 0.8700 - val_loss: 0.3190
Epoch 32/100
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9175 - loss: 0.2654 - val_accuracy: 0.8600 - val_loss: 0.3140
Epoch 33/100
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9125 - loss: 0.2609 - val_accuracy: 0.8600 - val_loss: 0.3102
Epoch 34/100
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9125 - loss: 0.2568 - val_accuracy: 0.8700 - val_loss: 0.3079
Epoch 35/100
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9125 - loss: 0.2532 - val_accuracy: 0.8600 - val_loss: 0.3035
Epoch 36/100
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9125 - loss: 0.2500 - val_accuracy: 0.8600 - val_loss: 0.3007
Epoch 37/100
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9150 - loss: 0.2457 - val_accuracy: 0.8800 - val_loss: 0.2992
Epoch 38/100
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9125 - loss: 0.2426 - val_accuracy: 0.8600 - val_loss: 0.2976
Epoch 39/100
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9175 - loss: 0.2399 - val_accuracy: 0.8700 - val_loss: 0.2928
Epoch 40/100
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9150 - loss: 0.2368 - val_accuracy: 0.8800 - val_loss: 0.2922
Epoch 41/100
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9200 - loss: 0.2339 - val_accuracy: 0.8700 - val_loss: 0.2882
Epoch 42/100
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9150 - loss: 0.2314 - val_accuracy: 0.8700 - val_loss: 0.2861
Epoch 43/100
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9150 - loss: 0.2289 - val_accuracy: 0.8600 - val_loss: 0.2837
Epoch 44/100
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9100 - loss: 0.2267 - val_accuracy: 0.8700 - val_loss: 0.2819
Epoch 45/100
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9150 - loss: 0.2243 - val_accuracy: 0.8700 - val_loss: 0.2824
Epoch 46/100
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9150 - loss: 0.2220 - val_accuracy: 0.8800 - val_loss: 0.2791
Epoch 47/100
100/100 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9200 - loss: 0.2201 - val_accuracy: 0.8700 - val_loss: 0.2793
Epoch 48/100
100/100 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9225 - loss: 0.2178 - val_accuracy: 0.8700 - val_loss: 0.2755
Epoch 49/100
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9175 - loss: 0.2162 - val_accuracy: 0.8700 - val_loss: 0.2745
Epoch 50/100
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9150 - loss: 0.2146 - val_accuracy: 0.8700 - val_loss: 0.2747
Epoch 51/100
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9175 - loss: 0.2126 - val_accuracy: 0.8700 - val_loss: 0.2717
Epoch 52/100
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9175 - loss: 0.2110 - val_accuracy: 0.8700 - val_loss: 0.2707
Epoch 53/100
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9150 - loss: 0.2100 - val_accuracy: 0.8800 - val_loss: 0.2698
Epoch 54/100
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9175 - loss: 0.2079 - val_accuracy: 0.8800 - val_loss: 0.2688
Epoch 55/100
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9200 - loss: 0.2070 - val_accuracy: 0.8800 - val_loss: 0.2681
Epoch 56/100
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9200 - loss: 0.2059 - val_accuracy: 0.8700 - val_loss: 0.2669
Epoch 57/100
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9225 - loss: 0.2043 - val_accuracy: 0.8800 - val_loss: 0.2681
Epoch 58/100
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9200 - loss: 0.2036 - val_accuracy: 0.8800 - val_loss: 0.2656
Epoch 59/100
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9175 - loss: 0.2023 - val_accuracy: 0.8700 - val_loss: 0.2647
Epoch 60/100
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9200 - loss: 0.2013 - val_accuracy: 0.8800 - val_loss: 0.2641
Epoch 61/100
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9150 - loss: 0.1999 - val_accuracy: 0.8800 - val_loss: 0.2635
Epoch 62/100
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9175 - loss: 0.1992 - val_accuracy: 0.8800 - val_loss: 0.2633
Epoch 63/100
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9250 - loss: 0.1985 - val_accuracy: 0.8800 - val_loss: 0.2638
Epoch 64/100
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9175 - loss: 0.1973 - val_accuracy: 0.8800 - val_loss: 0.2632
Epoch 65/100
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9200 - loss: 0.1966 - val_accuracy: 0.8800 - val_loss: 0.2617
Epoch 66/100
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9175 - loss: 0.1956 - val_accuracy: 0.8800 - val_loss: 0.2615
Epoch 67/100
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9175 - loss: 0.1946 - val_accuracy: 0.8800 - val_loss: 0.2608
Epoch 68/100
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9150 - loss: 0.1947 - val_accuracy: 0.8800 - val_loss: 0.2602
Epoch 69/100
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9150 - loss: 0.1931 - val_accuracy: 0.8800 - val_loss: 0.2605
Epoch 70/100
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9200 - loss: 0.1921 - val_accuracy: 0.8800 - val_loss: 0.2607
Epoch 71/100
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9175 - loss: 0.1922 - val_accuracy: 0.8800 - val_loss: 0.2605
Epoch 72/100
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9250 - loss: 0.1890 - val_accuracy: 0.8800 - val_loss: 0.2607
Epoch 73/100
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9275 - loss: 0.1908 - val_accuracy: 0.8800 - val_loss: 0.2592
Epoch 74/100
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9200 - loss: 0.1903 - val_accuracy: 0.8800 - val_loss: 0.2585
Epoch 75/100
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9200 - loss: 0.1890 - val_accuracy: 0.8800 - val_loss: 0.2581
Epoch 76/100
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9200 - loss: 0.1895 - val_accuracy: 0.8800 - val_loss: 0.2580
Epoch 77/100
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9150 - loss: 0.1886 - val_accuracy: 0.8800 - val_loss: 0.2592
Epoch 78/100
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9175 - loss: 0.1878 - val_accuracy: 0.8800 - val_loss: 0.2578
Epoch 79/100
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9175 - loss: 0.1876 - val_accuracy: 0.8800 - val_loss: 0.2576
Epoch 80/100
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9200 - loss: 0.1858 - val_accuracy: 0.8800 - val_loss: 0.2574
Epoch 81/100
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9225 - loss: 0.1859 - val_accuracy: 0.8800 - val_loss: 0.2575
Epoch 82/100
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9225 - loss: 0.1857 - val_accuracy: 0.8800 - val_loss: 0.2570
Epoch 83/100
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9200 - loss: 0.1856 - val_accuracy: 0.8800 - val_loss: 0.2583
Epoch 84/100
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9250 - loss: 0.1850 - val_accuracy: 0.8800 - val_loss: 0.2569
Epoch 85/100
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9200 - loss: 0.1840 - val_accuracy: 0.8800 - val_loss: 0.2571
Epoch 86/100
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9250 - loss: 0.1810 - val_accuracy: 0.8700 - val_loss: 0.2641
Epoch 87/100
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9150 - loss: 0.1840 - val_accuracy: 0.8800 - val_loss: 0.2567
Epoch 88/100
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9200 - loss: 0.1836 - val_accuracy: 0.8800 - val_loss: 0.2566
Epoch 89/100
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9150 - loss: 0.1830 - val_accuracy: 0.8800 - val_loss: 0.2565
Epoch 90/100
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9200 - loss: 0.1830 - val_accuracy: 0.8800 - val_loss: 0.2567
Epoch 91/100
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9175 - loss: 0.1811 - val_accuracy: 0.8800 - val_loss: 0.2574
Epoch 92/100
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9225 - loss: 0.1827 - val_accuracy: 0.8800 - val_loss: 0.2566
Epoch 93/100
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9225 - loss: 0.1824 - val_accuracy: 0.8800 - val_loss: 0.2564
Epoch 94/100
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9200 - loss: 0.1814 - val_accuracy: 0.8800 - val_loss: 0.2564
Epoch 95/100
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9225 - loss: 0.1816 - val_accuracy: 0.8800 - val_loss: 0.2567
Epoch 96/100
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9200 - loss: 0.1801 - val_accuracy: 0.8800 - val_loss: 0.2595
Epoch 97/100
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9225 - loss: 0.1785 - val_accuracy: 0.8800 - val_loss: 0.2590
Epoch 98/100
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9125 - loss: 0.1804 - val_accuracy: 0.8800 - val_loss: 0.2584
Epoch 99/100
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9225 - loss: 0.1808 - val_accuracy: 0.8900 - val_loss: 0.2572
Epoch 100/100
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9200 - loss: 0.1797 - val_accuracy: 0.8800 - val_loss: 0.2577